In [1]:
from keras.models import Sequential
from keras import layers
from keras.layers import Dense, GRU, Activation
import keras
import keras.utils as ku
from keras.preprocessing import sequence
import numpy as np
import pandas as pd
import time

Using TensorFlow backend.
/home/yes/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/yes/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [35]:
model = Sequential()

model.add(layers.Dense(500,activation='relu',input_shape=(100,3)))#,input_shape=(None,300)))
model.add(layers.Dense(300,activation='relu'))
#model.add(layers.Dense(500,activation='relu'))
model.add(layers.Dropout(0.4))
model.add(layers.LSTM(256, return_sequences=True))
model.add(layers.Dropout(0.2))
#model.add(layers.Dropout(0.4))         
model.add(layers.Dense((100),activation="relu"))

TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

In [32]:
#sgd = keras.optimizers.SGD(lr = 0.01, momentum=0.9)
#model.compile(loss='mean_squared_error', optimizer=sgd)
model.compile(loss='mean_squared_error',optimizer='rmsprop',metrics=["accuracy"])
#model.summary()

In [27]:
## set samps to how many samples you are using
## skip sample 0
import math
import re
samps = 4
for i in range(1, samps):
    j = 0
    ## this loop goes through each tick of the sample sim
    while True:
        #try:
            data = pd.read_csv(f"./FlockData2/sample{i}/Flock{j}.csv")
            target = pd.read_csv(f"./FlockData2/sample{i}/Flock{j+1}.csv")
            x = np.array(data['xcor'])
            x0 = np.zeros((100))
            y = np.array(data['ycor'])
            y0 = np.zeros((100))
            nearNei = np.zeros((100))
            nn = np.array(data['nearest-neighbor'])
            heading = np.zeros((100))
            h = np.array(data["heading"]) 
            xT = np.array(target['xcor'])
            x1 = np.zeros((100))
            yT = np.array(target['ycor'])
            y1 = np.zeros((100))
            for z in range(100):
                x0[z] = float(x[z])/17
                y0[z] = float(y[z])/17
                x1[z] = float(xT[z])/17
                y1[z] = float(yT[z])/17
                #nearNei[z] = int(re.findall(r'\d+', nn[z])[0])/100
                heading[z] = math.radians(int(h[i]))#[math.sin(math.radians(int(h[z]))),math.cos(math.radians(int(h[z])))]
            
            print("hello")
            inputs = np.zeros((1,100,3))
            inputs[0,:,0] = x0
            inputs[0,:,1] = y0
            inputs[0,:,2] = heading
            target = np.zeros((1,100,2))
            target[0,:,0] = x1
            target[0,:,1] = y1
            hist = model.train_on_batch(inputs,target)
            j +=1
        #except:
            print(hist)
            print(j)
            break

hello

ValueError: Error when checking target: expected dense_17 to have 2 dimensions, but got array with shape (1, 100, 2)

In [11]:

for e in range(5):
    print(f"epoch: {e}")
    startTime = time.perf_counter()
    for z in range(20):
        j = 0
        while True:
            try:
                target = pd.read_csv(f"./VirusData3/sample{z}/Virus{j+1}.csv")
                d = pd.read_csv(f"./VirusData3/sample{z}/Virus{j}.csv")
                x = np.array(d['xcor'])
                x0 = np.zeros((100))
                y = np.array(d['ycor'])
                y0 = np.zeros((100))
                target = np.array(target['sick?']).astype('float').reshape(1,100)
                #print(np.shape(target))
                s = np.array(d['sick?']).astype('float')#.reshape(1,100)
                for i in range(100):
                    try:      
                        if np.isnan(x[i]):
                            pass
                        else:
                            x0[i] = float(x[i])/17
                    except:
                        pass
                    try:
                        if np.isnan(y[i]):
                            pass
                        else:
                            y0[i] = float(y[i])/17
                    except:
                        pass

                    if np.isnan(s[i]):
                        s[i] = 0
                    elif s[i] == 0:
                        s[i] = -1
                    if np.isnan(target[0,i]):
                        target[0,i] = 0
                    elif target[0,i] == 0:
                        target[0,i] = -1

                #inputs = np.concatenate((x0,y0,s)).reshape(300,)
                #print(target)
                inputs = np.zeros((1,100,3))
                inputs[0,:,0] = x0
                inputs[0,:,1] = y0
                inputs[0,:,2] = s
                #inputs = inputs.reshape(1,100,3)
                #print(inputs)
                #print(target,i)
                hist = model.train_on_batch(inputs,target,reset_metrics=False)
                #print(j)
                #print(hist)
                j += 1
            except:
                print(model.metrics_names)
                print(hist)
                print(z)
                break
    print(f"Run Time: {time.perf_counter() - startTime}")
    print(model.metrics_names)
    print(hist)

model.summary()

epoch: 0
['loss', 'accuracy']
[0.5005645, 0.11731844]
0
['loss', 'accuracy']
[0.37, 0.08726004]
1
['loss', 'accuracy']
[0.35, 0.077192985]
2
['loss', 'accuracy']
[0.41, 0.07692308]
3
['loss', 'accuracy']
[0.28, 0.13972056]
4
['loss', 'accuracy']
[0.38, 0.120872974]
5
['loss', 'accuracy']
[0.29, 0.111839235]
6
['loss', 'accuracy']
[0.31, 0.12730004]
7
['loss', 'accuracy']
[0.3, 0.13794245]
8
['loss', 'accuracy']
[0.32, 0.13736099]
9
['loss', 'accuracy']
[0.26, 0.13926816]
10
['loss', 'accuracy']
[0.43, 0.12833418]
11
['loss', 'accuracy']
[0.5, 0.13607012]
12
['loss', 'accuracy']
[0.41, 0.13646194]
13
['loss', 'accuracy']
[0.27, 0.13346775]
14
['loss', 'accuracy']
[0.31, 0.13278085]
15
['loss', 'accuracy']
[0.53, 0.13666727]
16
['loss', 'accuracy']
[0.47, 0.13968143]
17
['loss', 'accuracy']
[0.5, 0.1433208]
18
['loss', 'accuracy']
[0.41, 0.1427876]
19
Run Time: 886.5168213900033
['loss', 'accuracy']
[0.41, 0.1427876]
epoch: 1
['loss', 'accuracy']
[0.5, 0.1401766]
0
['loss', 'accuracy']
[0.37, 0.13390736]
1
['loss', 'accuracy']
[0.35, 0.12852664]
2
['loss', 'accuracy']
[0.41, 0.13896987]
3
['loss', 'accuracy']
[0.28, 0.15144795]
4
['loss', 'accuracy']
[0.38, 0.14930817]
5
['loss', 'accuracy']
[0.29, 0.14517274]
6
['loss', 'accuracy']
[0.31, 0.1480852]
7
['loss', 'accuracy']
[0.3, 0.15099064]
8
['loss', 'accuracy']
[0.32, 0.15036881]
9
['loss', 'accuracy']
[0.26, 0.14941476]
10
['loss', 'accuracy']
[0.43, 0.14481603]
11
['loss', 'accuracy']
[0.5, 0.14649014]
12
['loss', 'accuracy']
[0.41, 0.1463799]
13
['loss', 'accuracy']
[0.27, 0.1419581]
14
['loss', 'accuracy']
[0.31, 0.1397395]
15
['loss', 'accuracy']
[0.53, 0.14185609]
16
['loss', 'accuracy']
[0.47, 0.14323005]
17
['loss', 'accuracy']
[0.5, 0.1449613]
18
['loss', 'accuracy']
[0.41, 0.14449131]
19
Run Time: 793.9915991820017
['loss', 'accuracy']
[0.41, 0.14449131]
epoch: 2
['loss', 'accuracy']
[0.5, 0.14554179]
0
['loss', 'accuracy']
[0.37, 0.1441197]
1
['loss', 'accuracy']
[0.35, 0.14103635]
2
['loss', 'accuracy']
[0.41, 0.14656591]
3
['loss', 'accuracy']
[0.28, 0.15315641]
4
['loss', 'accuracy']
[0.38, 0.15297952]
5
['loss', 'accuracy']
[0.29, 0.15053028]
6
['loss', 'accuracy']
[0.31, 0.15224499]
7
['loss', 'accuracy']
[0.3, 0.15388624]
8
['loss', 'accuracy']
[0.32, 0.153453]
9
['loss', 'accuracy']
[0.26, 0.1528021]
10
['loss', 'accuracy']
[0.43, 0.1498773]
11
['loss', 'accuracy']
[0.5, 0.15136237]
12
['loss', 'accuracy']
[0.41, 0.15120944]
13
['loss', 'accuracy']
[0.27, 0.14827028]
14
['loss', 'accuracy']
[0.31, 0.14665465]
15
['loss', 'accuracy']
[0.53, 0.14799888]
16
['loss', 'accuracy']
[0.47, 0.14884417]
17
['loss', 'accuracy']
[0.5, 0.14994499]
18
['loss', 'accuracy']
[0.41, 0.14960247]
19
Run Time: 785.9581976839982
['loss', 'accuracy']
[0.41, 0.14960247]
epoch: 3
['loss', 'accuracy']
[0.5, 0.1503107]
0
['loss', 'accuracy']
[0.37, 0.14930227]
1
['loss', 'accuracy']
[0.35, 0.14712572]
2
['loss', 'accuracy']
[0.41, 0.15085258]
3
['loss', 'accuracy']
[0.28, 0.15536214]
4
['loss', 'accuracy']
[0.38, 0.15520813]
5
['loss', 'accuracy']
[0.29, 0.15343152]
6
['loss', 'accuracy']
[0.31, 0.15459532]
7
['loss', 'accuracy']
[0.3, 0.15572703]
8
['loss', 'accuracy']
[0.32, 0.15539055]
9
['loss', 'accuracy']
[0.26, 0.15484628]
10
['loss', 'accuracy']
[0.43, 0.15269554]
11
['loss', 'accuracy']
[0.5, 0.15377875]
12
['loss', 'accuracy']
[0.41, 0.15363649]
13
['loss', 'accuracy']
[0.27, 0.15143503]
14
['loss', 'accuracy']
[0.31, 0.1501735]
15
['loss', 'accuracy']
[0.53, 0.15115698]
16
['loss', 'accuracy']
[0.47, 0.15176432]
17
['loss', 'accuracy']
[0.5, 0.15256953]
18
['loss', 'accuracy']
[0.41, 0.15183352]
19
Run Time: 783.2808225639892
['loss', 'accuracy']
[0.41, 0.15183352]
epoch: 4
['loss', 'accuracy']
[0.5, 0.15234989]
0
['loss', 'accuracy']
[0.37, 0.151556]
1
['loss', 'accuracy']
[0.35, 0.14988042]
2
['loss', 'accuracy']
[0.41, 0.15269345]
3
['loss', 'accuracy']
[0.28, 0.15610781]
4
['loss', 'accuracy']
[0.38, 0.15598169]
5
['loss', 'accuracy']
[0.29, 0.15455997]
6
['loss', 'accuracy']
[0.31, 0.15544572]
7
['loss', 'accuracy']
[0.3, 0.15631436]
8
['loss', 'accuracy']
[0.32, 0.1560456]
9
['loss', 'accuracy']
[0.26, 0.15564738]
10
['loss', 'accuracy']
[0.43, 0.15395096]
11
['loss', 'accuracy']
[0.5, 0.15299435]
12
['loss', 'accuracy']
[0.41, 0.15258232]
13
['loss', 'accuracy']
[0.27, 0.15085101]
14
['loss', 'accuracy']
[0.31, 0.14985706]
15
['loss', 'accuracy']
[0.53, 0.15024345]
16
['loss', 'accuracy']
[0.47, 0.15069982]
17
['loss', 'accuracy']
[0.5, 0.15128171]
18
['loss', 'accuracy']
[0.41, 0.15109524]
19
Run Time: 793.3949685520056
['loss', 'accuracy']
[0.41, 0.15109524]
Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 100, 500)          2000
_________________________________________________________________
dense_7 (Dense)              (None, 100, 300)          150300
_________________________________________________________________
dropout_3 (Dropout)          (None, 100, 300)          0
_________________________________________________________________
lstm_3 (LSTM)                (None, 256)               570368
_________________________________________________________________
dropout_4 (Dropout)          (None, 256)               0
_________________________________________________________________
dense_8 (Dense)              (None, 100)               25700
=================================================================
Total params: 748,368
Trainable params: 748,368
Non-trainable params: 0
_________________________________________________________________

In [853]:
data = pd.read_csv("./FlockData2/sample1/Flock0.csv")

In [854]:
data

    Unnamed: 0  heading       xcor       ycor nearest-neighbor
0            0    138.0   5.409268  11.607212      {turtle 95}
1            1     36.0  -0.273906  23.351505      {turtle 24}
2            2    333.5 -23.008609 -20.907030      {turtle 19}
3            3    171.0  29.255321 -17.202105       {turtle 7}
4            4    229.0  -5.615564  -6.508075      {turtle 79}
..         ...      ...        ...        ...              ...
95          95    163.0   3.300193  10.523441       {turtle 0}
96          96    195.0 -28.606687 -16.151167      {turtle 28}
97          97    327.0   8.523003 -27.302954      {turtle 13}
98          98     44.0  -9.782129 -17.488455      {turtle 88}
99          99    154.0 -12.400601 -25.464225       {turtle 5}

[100 rows x 5 columns]

In [14]:
x[0]

array([0, 51, -11.257439989152736, 10.630769666689213, False, 0, 0, 930.0],
      dtype=object)

In [16]:
data

,Unnamed: 0,heading,xcor,ycor,sick?,remaining-immunity,sick-time,age
0,0,51,-11.257440,10.630770,False,0,0,930.0
1,1,44,-2.362897,15.841234,False,0,0,137.0
2,2,72,-9.430460,-8.392363,False,0,0,234.0
3,3,277,6.136756,-15.891456,False,0,0,2091.0
4,4,199,-2.792280,-10.830074,True,0,1,1446.0
...,...,...,...,...,...,...,...,...
95,95,334,10.195878,-4.184493,False,0,0,1807.0
96,96,133,14.117419,-4.481686,False,0,0,1456.0
97,97,293,-7.854882,-8.621894,False,0,0,662.0
98,98,225,-16.804968,11.345687,False,0,0,477.0
99,99,240,-14.260687,8.349773,False,0,0,2437.0

In [17]:
d = pd.read_csv("./VirusData3/sample0/Flock0.csv")

,Unnamed: 0,heading,xcor,ycor,sick?,remaining-immunity,sick-time,age
0,0,61,7.013786929906611,-15.454478269450464,False,5.0,0.0,246.0
1,1,241,6.5647519526531015,9.153651747208142,False,41.0,0.0,2200.0
2,2,280,16.2305851595995,-1.7014778473373235,True,0.0,11.0,1555.0
3,3,312,-13.137895529721861,-4.9422270984384,False,4.0,0.0,1398.0
4,4,330,-7.485274248709061,-5.09413462989163,False,37.0,0.0,811.0
...,...,...,...,...,...,...,...,...
95,95,0,"""""",9.9,NaN,NaN,NaN,NaN
96,96,0,"""""",9.9,NaN,NaN,NaN,NaN
97,97,0,"""""",9.9,NaN,NaN,NaN,NaN
98,98,0,"""""",9.9,NaN,NaN,NaN,NaN
99,99,0,"""""",9.9,NaN,NaN,NaN,NaN

In [700]:
#norm info for virus
# area is 35x35
# but quards are divided by 17 to normalise [-17,17]
# age is out of 2600
# sick is bool
# dead is all 0
# how to represetn the time?
## first testing with just xcor/ycor/sick?
# output is whos sick
d = pd.read_csv("./VirusData3/sample0/Virus110.csv")

In [715]:
s = np.array(d['sick?']).astype('float').reshape(100)

In [702]:
x = np.array(d['xcor'])
x0 = np.zeros((100))
for i in range(100):
    try:
        x0[i] = float(x[i])/17
    except:
        pass
y = np.array(d['ycor'])
y0 = np.zeros(100)
for i in range(100):
    try:
        y0[i] = float(y[i])/17
    except:
        pass

In [703]:
x0
np.shape(y)
x0[0]

0.4658879245260742

In [711]:
bool(s[80] == np.nan)

False

In [488]:
inputs[0]

array([-0.66220235,  0.62533939,  0.        ])

In [721]:
b = s + np.zeros(100)
np.isnan(s[80])

np.where

True

In [456]:
array = np.arange(9)
array
array2D_1 = array.reshape((3,3))
array2D_1
 
array2D_2 = np.arange(10,19).reshape(3,3)
array2D_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [714]:
type(np.array(d['sick?'])[0])

bool

In [3]:
data = pd.read_csv("./FlockData2/sample3/Flock2.csv")

In [8]:
data

    Unnamed: 0     heading       xcor       ycor nearest-neighbor
0            0  156.000000  -5.395209 -24.665641      {turtle 80}
1            1  272.000000 -25.385335  13.860992      {turtle 13}
2            2   69.000000   3.830642   7.480479      {turtle 70}
3            3   41.000000 -14.605155  12.074471      {turtle 84}
4            4  329.000000  34.950435 -33.136267      {turtle 59}
..         ...         ...        ...        ...              ...
95          95  302.000000  28.773934 -27.336086      {turtle 28}
96          96  345.000000 -10.859039 -29.775489      {turtle 53}
97          97  171.000000  20.474674  -7.432057       {turtle 7}
98          98   85.772962  26.935956  23.464961      {turtle 61}
99          99   88.500000 -18.134094 -25.713853      {turtle 30}

[100 rows x 5 columns]

In [11]:
test_string = data["nearest-neighbor"][0]

In [14]:
res = [int(i) for i in test_string.split() if i.isdigit()]

In [15]:
import re
temp = re.findall(r'\d+', test_string)

In [18]:
int(temp[0])

80

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
heading

array([[ 0.99862953,  0.05233596],
       [ 0.99756405,  0.06975647],
       [ 0.99756405, -0.06975647],
       [ 0.9781476 ,  0.20791169],
       [ 0.9612617 , -0.27563736],
       [ 0.90630779,  0.42261826],
       [ 0.94551858,  0.32556815],
       [ 0.95105652,  0.30901699],
       [ 0.99862953,  0.05233596],
       [ 0.93969262,  0.34202014],
       [ 0.99862953,  0.05233596],
       [ 0.99756405, -0.06975647],
       [ 0.99862953, -0.05233596],
       [ 0.9961947 , -0.08715574],
       [ 0.99862953,  0.05233596],
       [ 0.99862953,  0.05233596],
       [ 0.99862953,  0.05233596],
       [ 0.9998477 ,  0.01745241],
       [ 0.99756405, -0.06975647],
       [ 0.98162718, -0.190809  ],
       [ 0.92718385,  0.37460659],
       [ 0.99939083,  0.0348995 ],
       [ 0.95105652, -0.30901699],
       [ 0.9781476 , -0.20791169],
       [ 0.98162718,  0.190809  ],
       [ 0.66913061,  0.74314483],
       [ 0.99939083,  0.0348995 ],
       [ 0.94551858,  0.32556815],
       [ 0.98162718,  0.190809  ],
       [ 0.95630476,  0.2923717 ],
       [ 0.9781476 ,  0.20791169],
       [ 0.9998477 , -0.01745241],
       [ 0.95105652,  0.30901699],
       [ 0.93358043,  0.35836795],
       [ 0.40673664,  0.91354546],
       [ 0.9961947 ,  0.08715574],
       [ 0.9998477 ,  0.01745241],
       [ 0.99862953,  0.05233596],
       [ 0.98162718, -0.190809  ],
       [ 0.99939083,  0.0348995 ],
       [ 0.9998477 , -0.01745241],
       [ 0.9781476 ,  0.20791169],
       [ 0.97437006,  0.22495105],
       [ 0.98480775, -0.17364818],
       [ 0.99756405,  0.06975647],
       [ 0.99862953,  0.05233596],
       [ 0.9781476 , -0.20791169],
       [ 0.98480775,  0.17364818],
       [ 0.92718385,  0.37460659],
       [ 0.90630779,  0.42261826],
       [ 0.91354546,  0.40673664],
       [ 0.89879405,  0.43837115],
       [ 0.98162718, -0.190809  ],
       [ 0.93969262,  0.34202014],
       [ 0.93358043,  0.35836795],
       [ 0.99939083,  0.0348995 ],
       [ 0.95630476,  0.2923717 ],
       [ 0.9998477 ,  0.01745241],
       [ 0.34202014,  0.93969262],
       [ 0.93969262,  0.34202014],
       [ 0.99862953, -0.05233596],
       [ 0.99756405, -0.06975647],
       [ 0.9998477 ,  0.01745241],
       [ 0.97437006, -0.22495105],
       [ 0.98768834,  0.15643447],
       [ 0.99939083,  0.0348995 ],
       [ 0.2923717 ,  0.95630476],
       [ 0.93358043,  0.35836795],
       [ 0.93358043,  0.35836795],
       [ 0.94551858,  0.32556815],
       [ 0.99862953,  0.05233596],
       [ 0.99756405, -0.06975647],
       [ 0.95630476,  0.2923717 ],
       [ 0.99756405, -0.06975647],
       [ 0.95630476, -0.2923717 ],
       [ 0.99862953,  0.05233596],
       [ 0.99862953, -0.05233596],
       [ 0.98768834,  0.15643447],
       [ 0.99756405, -0.06975647],
       [ 0.99862953,  0.05233596],
       [ 0.98162718, -0.190809  ],
       [ 0.87461971,  0.48480962],
       [ 0.98162718,  0.190809  ],
       [ 0.99862953, -0.05233596],
       [ 0.99862953,  0.05233596],
       [ 0.99862953, -0.05233596],
       [ 0.99862953, -0.05233596],
       [ 0.9961947 , -0.08715574],
       [ 0.83867057, -0.54463904],
       [ 0.9781476 ,  0.20791169],
       [ 0.99756405, -0.06975647],
       [ 0.9945219 , -0.10452846],
       [ 0.99862953, -0.05233596],
       [ 0.99756405, -0.06975647],
       [ 0.9998477 ,  0.01745241],
       [ 0.9961947 ,  0.08715574],
       [ 0.90630779,  0.42261826],
       [ 0.99862953, -0.05233596],
       [ 0.89100652,  0.4539905 ],
       [ 0.99254615, -0.12186934]])