In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
pd.read_csv("sample3/Flock1.csv",
                           skiprows=12,usecols=range(2,15))[0:100]

,heading,xcor,ycor,shape,label,label-color,breed,hidden?,size,pen-size,pen-mode,flockmates,nearest-neighbor
0,148,-5.801945725831984,-23.752095656837238,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 87 80 74 55},{turtle 80}
1,270,-24.385943955890056,13.82609225541946,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 45 29 54 13},{turtle 54}
2,61,2.89706194224053,7.1221111328707005,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 76 64 48 82 77 70},{turtle 70}
3,43,-15.261213988679684,11.319761134853378,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 57 84 29 54},{turtle 84}
4,331,35.465472850412404,-33.99343464051657,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 16 31 59},{turtle 59}
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,294,29.62198237364919,-27.866005058556023,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 28},{turtle 28}
96,347,-10.600220321715717,-30.741415127839506,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 8 11 56 53 34 87},{turtle 53}
97,169,20.318239456007007,-6.4443684370634795,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 19 79 89 7},{turtle 7}
98,83.77296157302015,25.938675721872094,23.39125233148781,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 58 73 38 61 75},{turtle 61}
99,90,-19.133751521043976,-25.740029472645723,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles 42 27 30 65 91 36},{turtle 30}

In [8]:
for j in range(0,200):
    print(j)
    i = 0
    while True:
        try:
            data = pd.read_csv(f"sample{j}/Flock{i}.csv",
                           skiprows=12,usecols=range(2,15))[0:100]
            data = data.drop(columns=["shape","label","label-color","breed","hidden?","size"
                       ,"pen-size","pen-mode","flockmates"])
            os.remove(f"sample{j}/Flock{i}.csv")
            data.to_csv(f"sample{j}/Flock{i}.csv")
            i+=1
        except:
            print(i)
            break

0
0
1
150
2
150
3
150
4
150
5
150
6
150
7
150
8
150
9
150
10
150
11
150
12
150
13
150
14
150
15
150
16
150
17
150
18
150
19
150
20
150
21
150
22
150
23
150
24
150
25
150
26
150
27
150
28
150
29
150
30
150
31
150
32
150
33
150
34
150
35
150
36
150
37
150
38
150
39
150
40
150
41
150
42
150
43
150
44
150
45
150
46
150
47
150
48
150
49
150
50
150
51
150
52
150
53
150
54
150
55
150
56
150
57
150
58
150
59
150
60
150
61
150
62
150
63
150
64
150
65
150
66
150
67
150
68
150
69
150
70
150
71
150
72
150
73
150
74
150
75
150
76
150
77
150
78
150
79
150
80
150
81
150
82
150
83
150
84
150
85
150
86
150
87
150
88
150
89
150
90
150
91
150
92
150
93
150
94
150
95
150
96
150
97
150
98
150
99
150
100
150
101
150
102
150
103
150
104
150
105
150
106
150
107
150
108
150
109
150
110
150
111
150
112
150
113
150
114
150
115
150
116
150
117
150
118
150
119
150
120
150
121
150
122
150
123
150
124
150
125
150
126
150
127
150
128
150
129
150
130
150
131
150
132
150
133
150
134
150
135
150
136
150
137
150
138
150
139
150
140
150
141
150
142
150
143
150
144
150
145
150
146
150
147
150
148
150
149
150
150
150
151
150
152
150
153
150
154
150
155
150
156
150
157
150
158
150
159
150
160
150
161
150
162
150
163
150
164
150
165
150
166
150
167
150
168
150
169
150
170
150
171
150
172
150
173
150
174
150
175
150
176
150
177
150
178
150
179
150
180
150
181
150
182
150
183
150
184
150
185
150
186
150
187
150
188
150
189
150
190
150
191
150
192
150
193
150
194
150
195
150
196
150
197
150
198
150
199
150