In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
globalParam= pd.read_csv("./sample3/Flock1.csv",
                           skiprows=8,usecols=range(1,15))[0:1]

,max-pxcor,min-pycor,max-pycor,perspective,subject,nextIndex,directed-links,ticks,max-align-turn,max-cohere-turn,max-separate-turn,minimum-separation,population,vision
0,35,-35,35,0,nobody,100,"""NEITHER""",2,0,1.5,4,3.75,100,0

In [11]:
data = pd.read_csv("./sample3/Flock1.csv",skiprows=12,
                  usecols=range(2,15))[0:100]

In [12]:
data

,heading,xcor,ycor,shape,label,label-color,breed,hidden?,size,pen-size,pen-mode,flockmates,nearest-neighbor
0,322,-27.033903552582252,-16.925122204634413,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0
1,44,-34.005921730858155,-14.639438196270799,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0
2,325,3.931034940668152,-23.34448152998646,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0
3,131,17.658640620127557,28.912609884683263,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0
4,200,28.56067156237522,10.528441679328957,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,140,29.923153049179255,27.32734887793005,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0
96,316,25.029091979697164,0.15841380991870357,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0
97,287,-24.226297144948774,6.594418372721069,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0
98,202,-11.577097720272967,-34.29843939292085,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0
99,145,23.026164018020758,25.087315960826864,"""default""","""""",9.9,{all-turtles},false,1.5,1.0,"""up""",{turtles},0.0

In [13]:
data = data.drop(columns=["shape","label","label-color","breed","hidden?","size"
               ,"pen-size","pen-mode","flockmates"])

In [10]:
data

   color heading                 xcor                 ycor  nearest-neighbor
0     47     322  -27.033903552582252  -16.925122204634413               0.0
1     43      44  -34.005921730858155  -14.639438196270799               0.0
2     47     325    3.931034940668152   -23.34448152998646               0.0
3     47     131   17.658640620127557   28.912609884683263               0.0
4     48     200    28.56067156237522   10.528441679328957               0.0
..   ...     ...                  ...                  ...               ...
95    44     140   29.923153049179255    27.32734887793005               0.0
96    49     316   25.029091979697164  0.15841380991870357               0.0
97    45     287  -24.226297144948774    6.594418372721069               0.0
98    46     202  -11.577097720272967   -34.29843939292085               0.0
99    48     145   23.026164018020758   25.087315960826864               0.0

[100 rows x 5 columns]

In [25]:
        for j in range(5,305):
            print(j)
            globalParams = pd.read_csv(f"./sample{j}/Flock0.csv",
                                       skiprows=8,usecols=range(1,15))[0:1]
            globalParams.to_csv(f"./sample{j}/globalParams.csv")
        
            i = 0
            while True:
                try:
                        data = pd.read_csv(f"./sample{j}/Flock{i}.csv",
                                           skiprows=12,usecols=range(2,15))[0:100]
                        data = data.drop(columns=["shape","label","label-color","breed","hidden?","size"
                       ,"pen-size","pen-mode","flockmates"])
                        #mod = pd.concat([globalParams,data])

                        os.remove(f"./sample{j}/Flock{i}.csv")
                        data.to_csv(f"./sample{j}/Flock{i}.csv")
                        i += 1
                except:
                        print(i)
                        break

5
200
6
200
7
200
8
200
9
200
10
200
11
200
12
200
13
200
14
200
15
200
16
200
17
200
18
200
19
200
20
200
21
200
22
200
23
200
24
200
25
200
26
200
27
200
28
200
29
200
30
200
31
200
32
200
33
200
34
200
35
200
36
200
37
200
38
200
39
200
40
200
41
200
42
200
43
200
44
200
45
200
46
200
47
200
48
200
49
200
50
200
51
200
52
200
53
200
54
200
55
200
56
200
57
200
58
200
59
200
60
200
61
200
62
200
63
200
64
200
65
200
66
200
67
200
68
200
69
200
70
200
71
200
72
200
73
200
74
200
75
200
76
200
77
200
78
200
79
200
80
200
81
200
82
200
83
200
84
200
85
200
86
200
87
200
88
200
89
200
90
200
91
200
92
200
93
200
94
200
95
200
96
200
97
200
98
200
99
200
100
200
101
200
102
200
103
200
104
200
105
200
106
200
107
200
108
200
109
200
110
200
111
200
112
200
113
200
114
200
115
200
116
200
117
200
118
200
119
200
120
200
121
200
122
200
123
200
124
200
125
200
126
200
127
200
128
200
129
200
130
200
131
200
132
200
133
200
134
200
135
200
136
200
137
200
138
200
139
200
140
200
141
200
142
200
143
200
144
200
145
200
146
200
147
200
148
200
149
200
150
200
151
200
152
200
153
200
154
200
155
200
156
200
157
200
158
200
159
200
160
200
161
200
162
200
163
200
164
200
165
200
166
200
167
200
168
200
169
200
170
200
171
200
172
200
173
200
174
200
175
200
176
200
177
200
178
200
179
200
180
200
181
200
182
200
183
200
184
200
185
200
186
200
187
200
188
200
189
200
190
200
191
200
192
200
193
200
194
200
195
200
196
200
197
200
198
200
199
200
200
200
201
200
202
200
203
200
204
200
205
200
206
200
207
200
208
200
209
200
210
200
211
200
212
200
213
200
214
200
215
200
216
200
217
200
218
200
219
200
220
200
221
200
222
200
223
200
224
200
225
200
226
200
227
200
228
200
229
200
230
200
231
200
232
200
233
200
234
200
235
200
236
200
237
200
238
200
239
200
240
200
241
200
242
200
243
200
244
200
245
200
246
200
247
200
248
200
249
200
250
200
251
200
252
200
253
200
254
200
255
200
256
200
257
200
258
200
259
200
260
200
261
200
262
200
263
200
264
200
265
200
266
200
267
200
268
200
269
200
270
200
271
200
272
200
273
200
274
200
275
200
276
200
277
200
278
200
279
200
280
200
281
200
282
200
283
200
284
200
285
200
286
200
287
200
288
200
289
200
290
200
291
200
292
200
293
200
294
200
295
200
296
200
297
200
298
200
299
200
300
200
301
200
302
200
303
200
304
96